### PR TITLE
add cache dir

### PR DESCRIPTION
**Pull request by saidbleik**
### Description
Add temp cache dir to load the tokenizer and model into

### Checklist:

- [ ] My code follows the code style of this project, as detailed in our [contribution guidelines](https://github.com/microsoft/nlp-recipes/blob/master/CONTRIBUTING.md).
- [ ] I have added tests.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by hlums** [comment]
I think you'll need to tear down the tmp directory manually at the end of the notebook, like in the last cell of [this notebook](https://github.com/microsoft/nlp-recipes/blob/master/examples/text_summarization/extractive_summarization_cnndm_aml_distributed.ipynb). Otherwise, the tmp directory will be there for a while or until you reboot the machine, I'm not exactly sure.

**Comment by saidbleik** [comment]
> 
> 
> I think you'll need to tear down the tmp directory manually at the end of the notebook, like in the last cell of [this notebook](https://github.com/microsoft/nlp-recipes/blob/master/examples/text_summarization/extractive_summarization_cnndm_aml_distributed.ipynb). Otherwise, the tmp directory will be there for a while or until you reboot the machine, I'm not exactly sure.

Shouldn't be a big deal. The most recent k dirs will stay until new tests are run.

**Comment by hlums** [comment]
> > I think you'll need to tear down the tmp directory manually at the end of the notebook, like in the last cell of [this notebook](https://github.com/microsoft/nlp-recipes/blob/master/examples/text_summarization/extractive_summarization_cnndm_aml_distributed.ipynb). Otherwise, the tmp directory will be there for a while or until you reboot the machine, I'm not exactly sure.
> 
> Shouldn't be a big deal. The most recent k dirs will stay until new tests are run.

@daden-ms I think you investigated this at one point and figured out tearing down the directories at the end of the notebook was necessary.

**Comment by daden-ms** [comment]
Yes, it might be helpful for the users if we put removing temp directory in the notebook. Some notebooks download large amounts of data and save the models multiple times and it can cost quite some disk space. If the user doesn't restart their machine often, it can cause a mysterious notebook and bash problems which can be hard to debug.

**Pull request merged**
